### ISSUE TITLE
币对数字可以固定宽度或者补零？

### ISSUE THREAD

**Issue by PatrickkZhao** [ocean2811/vscode-okx-tradingview#1]
有一些小额币对，小数点之后遇整时，文字长度会缩短。比如 0.1111 -> 0.1 ，这样状态栏整体就会抖动，比较影响注意力。
希望能够自定义宽度或者文本长度。

**Comment by degitcopl** [comment]
自定义文本长度或小数点位数不太合适,因为不同币对面值差异太大,这会导致用户必须针对每一个币对单独设置; 我先按照官方公布的每一个币对的最高价格精度,强行固定小数位数显示的数量,如果还不理想再考虑用户手动配置小数位数吧

**Comment by degitcopl** [comment]
该功能已在v0.0.6版本实现,更新插件即可

**Comment by ocean2811** [comment]
自定义文本长度或小数点位数不太合适,因为不同币对面值差异太大,这会导致用户必须针对每一个币对单独设置; 我先按照官方公布的每一个币对的最高价格精度,强行固定小数位数显示的数量,如果还不理想再考虑用户手动配置小数位数吧

该功能已在v0.0.6版本实现,更新插件即可

**Comment by PatrickkZhao** [comment]
反馈速度好快，十分感谢。
